### ISSUE TITLE
The description of the Set object is totally wrong currently

### ISSUE THREAD

**Issue by stof** [knpuniversity/javascript#5]
I'm talking about this chapter: knpuniversity.com/screencast/javascript-es6/set-object

currently, the description looks like this:

> The `Map` object is perfect for maps, or associative arrays as we call them in the PHP biz. ES2015 gives us another object called `Set`. This new fancy object replaces using true, indexed arrays. 
> // ...
> ep - the `Set` object is just like an array, but with some helper methods! Back up in loadRepLogs, after the for loop, let's see how this looks: `console.log(this.repLogs)`. Oh, and let's also use one of its helper methods: `this.repLogs.has(data.items[0])`. Obviously, this item should have been added to the `Set`!

This description is wrong. `Set` and `Array` are totally different data structures:

- `Array` is the ES representation of a sequence (and btw, it is an object with helper methods. you might like ``Array.prototype.includes`` in ES2016 for the example used in your current description)
- `Set` is the ES representation of ... a set, i.e. a data structure ensuring uniqueness of values in it.

The case of repLogs is a use case for Array, not for Set.

**Comment by stof** [comment]
btw, here is a way to implement Set on top of Map, which will show you that it does not behave like an array. It is actually a map where values and keys are the same.

```javascript
class Set {
    constructor(iterable = []) {
        this._map = new Map()

        for value of iterable {
            this.add(value)
        }
    }

    add(value) {
        if (!this._map.has(value)) {
            this._map.set(value, value)
        }
    }

    delete(value) {
        return this._map.delete(value)
    }

    has(value) {
        return this._map.has(value)
    }

    clear() {
        this._map.clear()
    }

    values() {
        return this._map.values()
    }

    entries() {
        return this._map.entries()
    }

    forEach(callback) {
        this._map.forEach(callback)
    }

    get size {
        return this._map.size
    }

    [Symbol.iterator]: () => this.values()
}
```

the signature for ``entries`` and ``forEach`` makes the analogy very clear btw.

Implementing WeakSet on top of WeakMap is left as an exercise to the reader (hint: works the same)

**Comment by stof** [comment]
Finding a use case for Set means finding a case where you want a set of elements without duplicates in it.

Regarding WeakSet, I agree with you about the missing use case. I never thought about a case where I want a weak set of elements without associated data.

**Comment by weaverryan** [comment]
I don't know how I breezed past the uniqueness part of this! It doesn't *technically* affect this example, because each object will be "unique" in memory, but you're right that, in spirit, it's wrong.

I'm going to look into updating this to use `Array` entirely, which of course as you mentioned still would show off a new method `includes`. Then, at the end, I can mention Set - if you have a "unique" situation.

**Comment by stof** [comment]
Well, as this chapter is about presenting the Set object, reworking the code to use Array looks wrong to me (having a new chapter to describe new goodies of the Array might be good though, be it ``includes`` of the new methods coming from the unified collection iteration API). It would be better to find a use case for Set instead (one relying on the uniqueness)

**Comment by weaverryan** [comment]
I've just done this (more or less) - that chapter is now about both, but first we use `Array` (in place of `Set`, but for the same purpose) and then I quickly show `Set` at the end in the `play.js` file (branded basically as an Array-like object, but with uniqueness, and different method names, like `add` instead of `push`).

You can see the final "steps" here: https://github.com/knpuniversity/javascript/commits/tmp-finished - the 3 steps starting with "Array:" and the 2 starting with "Set:".
